
// const ROOT_URL = (
//   process.env.NEXT_PUBLIC_URL ||
//   (process.env.VERCEL_PROJECT_PRODUCTION_URL
//     ? `https://${process.env.VERCEL_PROJECT_PRODUCTION_URL}`
//     : "http://localhost:3000")
// ).trim();

// export const minikitConfig = {
  // accountAssociation: {
  //   "header": "eyJmaWQiOjEwNTAyNjgsInR5cGUiOiJjdXN0b2R5Iiwia2V5IjoiMHhkM2U4MzhFQThmMjczYzdkMzlDNmViMzUxMDMwOGJGNUNkYUUyY2VFIn0",
  //   "payload": "eyJkb21haW4iOiJtaW50LnBlcnNvbmFsaWRzLnh5eiJ9",
  //   "signature": "sZBMFygdlbt5QDf2mGFW984Hek0qfWIOwjeYltVD3HogwvctWdu5IubQNZDf0A0Vinra0QJk1tCcHJb5ZJqrSxs="
  // },

//   miniapp: {
//     version: "1",
//     name: "Personal ID Mint",
//     subtitle: "Onchain ID Mint",
//     description:
//       "Mint a unique Onchain ID on Base. Features Daily Check-in to build a streak and share progress on social media.",
//     tagline: "Mint your onchain identity",
//     ogTitle: "Personal ID Mint",
//     ogDescription: "Mint a unique onchain ID on Base with daily check-in streaks.",
//     ogImageUrl: `${ROOT_URL}/og.png`,
//     noindex: false,

//     capabilities: {
//       wallet: {

//         smartWalletOnly: false, 
//       },
//       atomicBatch: true, 
//     },

//     screenshotUrls: [`${ROOT_URL}/screenshot-portrait.png`],
//     iconUrl: `${ROOT_URL}/icon.png`,
//     heroImageUrl: `${ROOT_URL}/hero.png`,
//     splashImageUrl: `${ROOT_URL}/hero.png`,
//     splashBackgroundColor: "#000000",
//     homeUrl: ROOT_URL,
//     webhookUrl: `${ROOT_URL}/api/webhook`,
//     requiresAccountAssociation: true, 
//     primaryCategory: "social",
//     tags: ["identity", "mint", "onchain", "streak", "social"],
//   },

//   frame: {
//     version: "1",
//     name: "Personal ID Mint",
//     iconUrl: `${ROOT_URL}/icon.png`,
//     splashImageUrl: `${ROOT_URL}/hero.png`,
//     splashBackgroundColor: "#000000",
//     action: {
//       type: "launch_frame",
//       name: "Mint ID",
//       url: ROOT_URL,
//     },
//   },
// };
















import type { MiniAppManifest } from "@coinbase/onchainkit/minikit";


const ROOT_URL = "https://mint.personalids.xyz";


export const minikitConfig: MiniAppManifest = {

accountAssociation: {
  header: "eyJmaWQiOi0xLCJ0eXBlIjoiYXV0aCIsImtleSI6IjB4MTcyNzdiMjliZEQ4MGY0NEM5QkY1RjAzQUM4MzdjOTc2N0NmNjQzYSJ9",
  payload: "eyJkb21haW4iOiJtaW50LnBlcnNvbmFsaWRzLnh5eiJ9",
  signature: "AAAAAAAAAAAAAAAAyhG94Fl3s2MRZwKIYr4qFzl2yhEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAxgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC8SCrVbLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABqAAAAAAAAAAAAAAAABf8TfUsP3NSdyjDHz1fleKAm0niQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFxB-tlIwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAABcneym92A9Eyb9fA6yDfJdnz2Q6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAABcneym92A9Eyb9fA6yDfJdnz2Q6AAAAAAAAAAAAAAAAAAAAAAAAAAAAACEFAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABW7gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAtxsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbEMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAqAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADELCq9HgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkDw8_JAAAAAAAAAAAAAAAAH1T547ljd_3cD5jkPt8F_lBMZsxAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABLTFAa1Ss4zVs3c6EMXzqVGa7ZvRZaBd4lsqn3J1eZBVE7Sc75XduSaE-EqE7XbSCnOd1l-xHzA6nKRhEh10kHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAl8ZgIay2xclZzG8RWZzuWvO8j9R0fus3XxDee9lRlVy8dAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACKeyJ0eXBlIjoid2ViYXV0aG4uZ2V0IiwiY2hhbGxlbmdlIjoiT0FrNzNlQ2x4ZjZPMmVJSUNqR3JXaWNWWHRvQzlMXzZiYkgtQzl1aUNOZyIsIm9yaWdpbiI6Imh0dHBzOi8va2V5cy5jb2luYmFzZS5jb20iLCJjcm9zc09yaWdpbiI6ZmFsc2V9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABf8TfUsP3NSdyjDHz1fleKAm0niQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAERB-tlIwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAABcneym92A9Eyb9fA6yDfJdnz2Q6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAABcneym92A9Eyb9fA6yDfJdnz2Q6AAAAAAAAAAAAAAAAAAAAAAAAAAAAACEFAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABu7gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAtxsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbY8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADkLCq9HgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABEKVZeOxp4H9uuIehphm1QXaIyy68M7wC_Qov7f8BPvaOA-tFx1vLKphtoIQD_uKR0D-KoPKeM7afsvkuUmOOAR7JCt5UAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQYyv0vwqQTAd1GPpkUBjTnNZARUYz-oVM0Qjaj07-DawKeasPcfllxHDwjTwXmaUwuybJNnaAdK58Npa2AAdenwbAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAqAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAXAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGurE9S414F7POPxBs7fvQkjs6TAlHC3smpLumwsl62kmyTBFUr9lU5IHFhqR7ToOha_Httq_EpZo6MZD4qxkHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACXxmAhrLbFyVnMbxFZnO5a87yP1HR-6zdfEN572VGVXLx0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAL57InR5cGUiOiJ3ZWJhdXRobi5nZXQiLCJjaGFsbGVuZ2UiOiJtWEt6ZGxSdElEWmtNYTlPNVFlWjZaYmQyYWJUM3hLVzVvQTdYWmxwU0xzIiwib3JpZ2luIjoiYW5kcm9pZDphcGsta2V5LWhhc2g6RUFPV3dPUUFCaHNRWGRsZ0dpNWhCT2FkeDdUWTZaWF9DcUpscG94ZjFoayIsImFuZHJvaWRQYWNrYWdlTmFtZSI6Im9yZy50b3NoaSJ9AABkkmSSZJJkkmSSZJJkkmSSZJJkkmSSZJJkkmSSZJJkkg"
},



  // accountAssociation: {
  //   header: "eyJmaWQiOjEwNTAyNjgsInR5cGUiOiJjdXN0b2R5Iiwia2V5IjoiMHhkM2U4MzhFQThmMjczYzdkMzlDNmViMzUxMDMwOGJGNUNkYUUyY2VFIn0",
  //   payload: "eyJkb21haW4iOiJtaW50LnBlcnNvbmFsaWRzLnh5eiJ9",
  //   signature: "sZBMFygdlbt5QDf2mGFW984Hek0qfWIOwjeYltVD3HogwvctWdu5IubQNZDf0A0Vinra0QJk1tCcHJb5ZJqrSxs=",
  // },


  miniapp: {
    version: "1",
    name: "Personal ID Mint",
    subtitle: "Onchain ID Mint",
    description:
      "Mint a unique Onchain ID on Base. Features Daily Check-in to earn rewards and share progress on social media.",
    screenshotUrls: [`${ROOT_URL}/screenshot-portrait.png`],
    iconUrl: `${ROOT_URL}/icon.png`,
    splashImageUrl: `${ROOT_URL}/hero.png`,
    splashBackgroundColor: "#000000",
    homeUrl: ROOT_URL,
    webhookUrl: `${ROOT_URL}/api/webhook`,
    primaryCategory: "utility",
    tags: ["identity", "mint", "onchain", "rewards"],
    heroImageUrl: `${ROOT_URL}/hero.png`,
    tagline: "Mint your onchain identity",
    ogTitle: "Personal ID Mint",
    ogDescription: "Mint a unique onchain ID on Base with daily check-in Rewards",
    ogImageUrl: `${ROOT_URL}/og.png`,
  },
} as const;